### ISSUE TITLE
Videos played via the in-player video list along the bottom of the player now have issues playing

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#101]
Caused by https://github.com/denverpost/dptv/issues/17

**Comment by danielpetty** [comment]
Just checking to see whether this is the issue of videos cycling through a list (like 5-6 of them), before it actually plays a video. Here's an example: http://dpo.st/1rK6q7q

**Comment by schneidan** [comment]
As of this morning I now see this affecting iframe embeds. Clicking play on listed video triggers this "cycling" behavior, and after cycling through a (seemingly random) number of videos and flashing the thumbnail for a second or two, the player eventually settles on and plays an unrelated video. Unable to watch embedded videos on NGPS. 

Chrome on Windows 7, replicated in Chrome on Mac.

Example article with malfunctioning iframe: http://www.denverpost.com/news/ci_27245548/argentina-extradite-former-fema-agent-denver-murder-charge

That said, once it starts playing, it seems to successfully continue playing next videos until it eventually gets back around to the one I wanted.

**Comment by freejoe76** [comment]
I haven't gotten that behavior last night or tonight on my tests, that said, this is something that needs to be fixed.

**Comment by danielpetty** [comment]
I was seeing this on Chrome on a Mac running Yosemite.

**Comment by freejoe76** [comment]
I've disabled auto-playing the next video and filed a trouble ticket with Ooyala regarding the non-working methods in its API ( player.play() and player.playMovie() ).
