### ISSUE TITLE
Black bars on left and right side of video screen

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#103]
Videos when played are letterboxing with black bars are on the left and right of the video. Adjust to 16:9 aspect ratio.

**Comment by freejoe76** [comment]
Please add a URL to this issue.

**Comment by freejoe76** [comment]
On hold until more description is given.

**Comment by danielpetty** [comment]
Example, when video is playing -- black bars on the left and right:

http://sportsshow.denverpost.com/2015/01/07/les-and-woody-s-top-six-nfl-mvp-candidates/

**Comment by freejoe76** [comment]
Thanks.

**Comment by freejoe76** [comment]
This is finished on DPTV and Sports Show.
