### ISSUE TITLE
SportsShow individual player is not serving pre-roll ads

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#105]
Examples:
http://sportsshow.denverpost.com/2015/01/05/you-gotta-see-this-you-re-outta-ya-freakin-mind-cowturd/
http://sportsshow.denverpost.com/2015/01/05/should-the-nfl-playoff-expand/
http://sportsshow.denverpost.com/2015/01/05/chris-christie-and-jerry-jones-need-to-get-a-room/

Reproduced on Safari on OS X Yosemite 10.10.1.

**Comment by freejoe76** [comment]
I'd get @LCLambert on this issue, Dan.

**Comment by LCLambert** [comment]
Thanks for the notice team. Let me get my team to investigate as there
should be ROS serving into this space.

Lance C. Lambert
Director of Digital Products & Platforms
Digital First Media | The Denver Post

LCLambert@DenverPost.com
o: 303.954.1711 | c: 805.746.1921

**Comment by freejoe76** [comment]
Is there an update on this?

**Comment by Leo-Pacheco** [comment]
The issue appeared to have been resolved last week. Pre-rolls were play fine.
I just reviewed the DPTV and Sports Show pages a few minutes ago, and did not see a pre-roll. However, I did review all current pre-roll ad campaigns and they are all pacing over their goals by 30%. So we may be serving more video plays than what is booked for pre-roll ads.

I will post a new DC Support Team ticket and have them review the DPTV and Sports Show pages again, and see if they are set up to accept pre-rolls from our ad exchange.

**Comment by freejoe76** [comment]
Thanks Leo!

**Comment by Leo-Pacheco** [comment]
A wild Pre-roll appeared!.
![dp sports show 150113](https://cloud.githubusercontent.com/assets/10427399/5728478/c31a895e-9b27-11e4-9554-38ff9e55e2bf.JPG)

**Comment by danielpetty** [comment]
We had about 60,000 video views yesterday and I heard advertising had only booked like 50K for the month of January. I was not seeing many ads yesterday. cc: @LCLambert @utahras

**Comment by LCLambert** [comment]
Hi Team,

So the confusion was our bad. We have had demand outweigh supply in the
video space for about a year now. Thanks to the efforts around DPTV, the
tables have turned. As Dan stated, our targeted impressions are actually
less than the number of video plays. This is a good problem for us! We have
alerted the digital sales team so they can start selling into this space
again. Likewise we have reached out to Kevin Bowen at corporate for remnant
to serve when needed.

Note; We have also put a request going forward for 15-second only pre-roll
if in the can and not produced in-house.

Best,

Lance C. Lambert
Director of Digital Products & Platforms
Digital First Media | The Denver Post

LCLambert@DenverPost.com
o: 303.954.1711 | c: 805.746.1921

**Comment by freejoe76** [comment]
Closing issue, seems to be resolved.

**Comment by LCLambert** [comment]
Thanks.

Lance C. Lambert
Director of Digital Products & Platforms
Digital First Media | The Denver Post

LCLambert@DenverPost.com
o: 303.954.1711 | c: 805.746.1921
