### ISSUE TITLE
Deliver DPTV/Sports Show content over HTTPS

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#107]
Turn DPTV and Sports Show so they're delivering content on the Wordpress site over HTTPS for improved SEO and more secure browsing.

More here: http://open.blogs.nytimes.com/2014/11/13/embracing-https/

h/t @freejoe76

**Comment by freejoe76** [comment]
Note: HTTPS is already enabled on DPTV's in-stream players.

Making HTTPS work on the http://denverpost.com/sportsshow and http://denverpost.com/dptv URLs is going to be a separate challenge, I may break that out into a distinct issue.

**Comment by danielpetty** [comment]
Ahh, yes, that's what I was talking about. I may not have said it correctly.

**Comment by freejoe76** [comment]
Which part was the part you were talking about?

**Comment by danielpetty** [comment]
URLs should be https:// instead of http:// as below:

https://sportsshow.denverpost.com/2015/01/06/former-nugget-j-r-smith-is-traded-to-cleveland-cavaliers/

**Comment by freejoe76** [comment]
Right right. The caveat there is all page assets must be also delivered via https, otherwise it's not truly secure.

**Comment by danielpetty** [comment]
Much more complicated then, yes. That would involve delivering content on extras over HTTPS. And of course, if the goal is to move to www instead of a subdomain, that's almost impossible.

**Comment by freejoe76** [comment]
We're now on akamai, and SSL certs are even more expensive on akamai (per https://github.com/denverpost/dptv/issues/121), so I'm wontfixing this.
