### ISSUE TITLE
Facebook OpenGraph error for multuple og:url values

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#109]
For this URL (and I assume all article pages):

`Object at URL 'http://sportsshow.denverpost.com/2015/01/08/brandon-stokley-says-why-it-s-retired-for-good/' of type 'video.other' is invalid because it specifies multiple 'og:url' values: http://sportsshow.denverpost.com/2015/01/08/brandon-stokley-says-why-it-s-retired-for-good/, http://sportsshow.denverpost.com/2015/01/08/brandon-stokley-says-why-it-s-retired-for-good/.`

**Comment by freejoe76** [comment]
http://sportsshow.denverpost.com/2015/01/08/brandon-stokley-says-why-it-s-retired-for-good/

**Comment by freejoe76** [comment]
Looks like the Yoast SEO plugin's doing this. I'll look into it.

**Comment by freejoe76** [comment]
Fixed.

**Comment by freejoe76** [comment]
Also fixed this on DPTV.
