### ISSUE TITLE
Changes in Sports Show on page Categories and pod player

### ISSUE THREAD

**Issue by utahras** [denverpost/dptv#111]
THE SPORTS SHOW page

Categories for bottom of page these labels are in Ooyala. Top to bottom, left to right.

The Sports Show
Full Episodes
Sports

** Guests
** Broncos
** Woodys World

** The Big Stuff
** Dope Of The Day
** Pick 6

** Pop-A-Shot
** Social Animals
** You Gotta See This!

** NFL/Broncos
** NBA/Nuggets
** MLB/Rockies

** NHL/Avalanche
** DPtv (replace Up To Date with this)
News

These are what is in the pods now for the player

Full Episodes
The Big Stuff
Woody’s World
Sports
Guests
Dope Of The Day
Pick 6
Pop-A-Shot
Social Animals
You Gotta See This!

CODE FOR POD PLAYER:
```
<div id="playerContainer" ></div>
<script type="text/javascript" src="https://player.ooyala.com/v3/aceb741323cd43cc820ce3ea8ed4d44e"></script>
<script type="text/javascript">
var ooyalaPlayer;

OO.ready(function() {
    var playerConfiguration = {
        playlistsPlugin: {"data":["b5728073272c4408995a6871c1bbf870","198b1bbf704343a2a4cd6ab812a0d947","fcc6ebdbfcfb4b67a2b899c4ad1d1f8a","3db994ee74fe4b59a6510b1c79295196","8e3535d0970e4ee3b1d34f8e425c2950","7de2b1ed282a467c959f01509176d1bd","1e5912b94ffc47d38f8e5973ab3d2ac7","2fb6e161221b4bb1aa5ee045d04282ae","2a51ae3d8bfb4ca1a2d4fe20563da151","9a1c5c4e2fdf49c793fcad9d6d8a820a"]},
        autoplay: false,
        loop: false,
        height: '',
        width: '',
        useFirstVideoFromPlaylist: true
    };

    ooyalaPlayer = OO.Player.create('playerContainer', '', playerConfiguration);
});

</script>



```

**Comment by freejoe76** [comment]
** = new category

**Comment by freejoe76** [comment]
Okay Tim ( @utahras ), the new categories for the Sports Show are created. To start populating them I need videos in Ooyala assigned to those labels. I'll finish this task after that gets done.

**Comment by freejoe76** [comment]
The labels are now hooked up to the categories and will begin populating.

**Comment by freejoe76** [comment]
This is finished.
