### ISSUE TITLE
Changes in DPTV on page Categories and pod player 

### ISSUE THREAD

**Issue by utahras** [denverpost/dptv#112]
This also need to be addressed so we can complete the workflow change.

DPTV page changes in pod player and categories at the bottom of the page.:

Categories Bottom Of Page

Up To Date
** Behind The Headlines
News

**Newsmakers
** Reaction Shot
Cannabist

Denver Post Films
**Game On
**Sports

Pod Player:
DPTV
Up To Date
Behind The Headlines
News
Reaction Shot
Newsmakers
Cannabist

CODE for player
```



```

**Comment by utahras** [comment]
I added an additional category called Newsmakers and added it to the pod player, updated code below. RAS


<div id="playerContainer" ></div>
<script type="text/javascript" src="https://player.ooyala.com/v3/df3e4364f37c45d09283f7d098c03fce"></script>
<script type="text/javascript">
var ooyalaPlayer;

OO.ready(function() {
    var playerConfiguration = {
        playlistsPlugin: {"data":["5ec0b4f104fc4cfebd63380310dfc1f5","6eb0563f2cc94b1094d16d036f80f703","4aa8fd4e4b7c425795dd8663094e41db","784c4a2e634246dfa67e28069413a3d4","17ba4c74d0dc4f10b9eb8c34f2975a09","baa0e33703b84fcfaf9e06e41451c017","7de2b1ed282a467c959f01509176d1bd","d9b6afb63faa4b18be72463d516b5fbe","a8e521272fcc49a680fc3fb22b8a35e9"]},
        autoplay: false,
        loop: false,
        height: '',
        width: '',
        useFirstVideoFromPlaylist: true
    };

    ooyalaPlayer = OO.Player.create('playerContainer', '', playerConfiguration);
});

</script>

**Comment by freejoe76** [comment]
Hi Tim ( @utahras ), the new categories for DPTV are created. To start populating them I need videos in Ooyala assigned to those labels. I'll finish this task after that gets done.

**Comment by freejoe76** [comment]
The new categories are now hooked up to their corresponding labels.

**Comment by freejoe76** [comment]
Hi @utahras I need the new code for the player. If you can tell me where it is so I can go get it that works too.

**Comment by freejoe76** [comment]
Closing. If there's anything else you need please open a new issue.
