### ISSUE TITLE
Create new player for post pages, without the row of videos on the bottom

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#119]
Both DPTV and Sports Show

**Comment by freejoe76** [comment]
This is done on DPTV.

**Comment by freejoe76** [comment]
Done on Sports Show.

**Comment by danielpetty** [comment]
I see on sports show at the article level that the aspect ratio doesn't appear to be 16:9.

http://sportsshow.denverpost.com/2015/02/04/pick-6-top-free-agents-who-broncos-must-re-sign/

Black bars are at the top and bottom. I believe the height should be 563 pixels. Width remains at 1000 pixels.

**Comment by freejoe76** [comment]
Thanks Dan I'll look into that.

**Comment by freejoe76** [comment]
Okay that's fixed too.
