### ISSUE TITLE
Sports Show Full Epsiodes are porting over and creating separate posts again

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#122]
When uploaded and tagged with "The Sports Show" and "Full Episodes," The Sports Show full episode is coming over from Ooyala and creating a separate post. We want it to not come over to Wordpress.

**Comment by freejoe76** [comment]
Did anything change on the video production workflow? New labels being assigned, labels being moved around, anything such as that? cc @utahras

**Comment by freejoe76** [comment]
@danielpetty is this still happening?

**Comment by freejoe76** [comment]
Also, @danielpetty, what happened to the Full Episode posts? The last one on http://sportsshow.denverpost.com/category/sports-show/full-episode/ published Jan. 21.

**Comment by danielpetty** [comment]
Still happening, but does not matter now because they become drafts. I need to send a reminder on how to produce the full episode posts correctly.

**Comment by freejoe76** [comment]
@danielpetty Is this issue still a problem?

**Comment by danielpetty** [comment]
It's still creating them, but it doesn't matter now because we can just delete the drafts. Now, they're aren't publishing live.

**Comment by freejoe76** [comment]
Thanks. I'll close this.
