### ISSUE TITLE
YouTube website verification 

### ISSUE THREAD

**Issue by amybrothers** [denverpost/dptv#129]
I need to verify new YouTube Channels
```
DPTV: <meta name="google-site-verification" content="uxhoEE2xNKcBhEFrDS6PQ3gZXlwIFvY91KWBwezbghs" />
The Sports Show:  <meta name="google-site-verification" content="uxhoEE2xNKcBhEFrDS6PQ3gZXlwIFvY91KWBwezbghs" />
```
Thank you,
And please let me know when you are done.
Amy

**Comment by freejoe76** [comment]
Thanks Amy,

I know this is extra work to get something done, but in the long run it's easier to manage. I just made these changes and pushed them to the sites. If something is wrong, just re-open this issue.

-Joe
