### ISSUE TITLE
The Sports Show category page looks like it's a mistake.

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#132]
http://sportsshow.denverpost.com/category/sports-show/

**Comment by freejoe76** [comment]
Note: This only happens during Sports Show livestreams, between 1pm and 3pm on weekdays.

**Comment by danielpetty** [comment]
Note also per our workflow that once the full episode is posted, we sub out the live player. That can take a while to process because it's a two-hour show.

**Comment by freejoe76** [comment]
This is fixed.
