### ISSUE TITLE
Multiple Wordpress posts for the same video publish when ooyala video is imported

### ISSUE THREAD

**Issue by ericjlubbers** [denverpost/dptv#133]
Several hundred posts of the Behind the Headlines: Interview with Police Chief Robert White video have been made overnight to DPTV.

**Comment by freejoe76** [comment]
I put in a fix for this on DPTV, about to put in a fix on Sports Show. Let me know if you see it happening again.

**Comment by freejoe76** [comment]
Put in fix for the Sports Show.

**Comment by danielpetty** [comment]
Thank you much. It was also a ton of Sports Show pieces as well.

**Comment by freejoe76** [comment]
This is fixed.
