### ISSUE TITLE
Rework homepage/section pages to use single video player without strip of videos; replace strip with WP output

### ISSUE THREAD

**Issue by schneidan** [denverpost/dptv#134]
Along with https://github.com/denverpost/dptv/issues/119 I suggest using a single player everywhere, and replicating the "row of videos below" behavior with output from Wordpress rather than Ooyala.

This would give more control over display of those videos, and reduce the load and clunkiness of that "playlist player" on mobile/tablet, which is currently a fairly bad use experience.

Applies to DPTV and Sports Show.

**Comment by freejoe76** [comment]
WONTFIX
