### ISSUE TITLE
Go back to autoposting Up To Date

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#138]

**Comment by danielpetty** [comment]
If possible, would be preferrable to just take a feed of the posts from dptv.denverpost.com to reflect all changes made.

**Comment by freejoe76** [comment]
Yea, that has SEO benefits as well.

**Comment by freejoe76** [comment]
Until we build in the functionality to publish on Sports Show from an RSS feed (which would be a separate issue), I'm just going to make autoposting autpost Up To Date. And by "going to make" I mean "I just made." This is done.
