### ISSUE TITLE
Adding volume button to DPTV/Sports Show video player

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#140]
After speaking with @utahras, we are requesting the addition of the volume button on the DPTV and Sports Show player, which appears to be in the API.

**Comment by freejoe76** [comment]
There's no point in a volume interface unless it also controls the volume on advertisements. Currently it won't ([see this information](https://github.com/denverpost/dptv/issues/170#issuecomment-86722624)). User interface is about trust, a volume slide that doesn't do anything breaks that trust.

**Comment by freejoe76** [comment]
Ooyala plans on releasing changes that allow this to happen sometime in 2016.
