### ISSUE TITLE
www.denverpost.com/sportsshow doesn't work in mobile, we shouldn't link to it.

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#142]
www.denverpost.com/sportsshow doesn't work on handheld devices. Same is true for DPTV. link to the non-www instead.

**Comment by ericjlubbers** [comment]
FYI, just happened to noticed this bug. Those URLs just need a mobile redirect exception at the Akamai level. I will file the ticket.

**Comment by ericjlubbers** [comment]
Jeff Howell confirms mobile exceptions are now in place. Closing.
