### ISSUE TITLE
Multiple Wordpress posts (again) on DPTV

### ISSUE THREAD

**Issue by ericjlubbers** [denverpost/dptv#143]
Seeing hundreds of Game On, Peyton Manning and Reaction Shot videos in Draft status in the DPTV dashboard. 1,200 and counting.

**Comment by freejoe76** [comment]
Okay, I'm trying something else out now, let's see if it works.

**Comment by danielpetty** [comment]
Still seeing massive draft post repeats flowing into The Sports Show:

http://sportsshow.denverpost.com/wp-admin/edit.php?post_status=draft&post_type=post

**Comment by freejoe76** [comment]
Added a plugin to allow bulk-delete of drafts.

**Comment by freejoe76** [comment]
Whatever's going wrong is only going wrong on production. Haven't been able to replicate this on local WP install.

**Comment by freejoe76** [comment]
Okay I've put up another attempt at fixing this onto DPTV, let's see if it works.

**Comment by freejoe76** [comment]
That didn't work. Trying something else.

**Comment by freejoe76** [comment]
Found a promising lead on the issue.

**Comment by freejoe76** [comment]
OKAY THIS UPDATE LOOKS PROMISING. I'm going to turn my attention elsewhere now and let the afternoon play out, will close this at the end of the day if it's still fixed then.

**Comment by freejoe76** [comment]
This is fixed!
