### ISSUE TITLE
Added Categories now showing up

### ISSUE THREAD

**Issue by utahras** [denverpost/dptv#144]
The new categories have not shown up, checked for drafts which here are 49, but all the same to posts.

This is CRITICAL  functionality that needs to be completed.

**Comment by freejoe76** [comment]
Hi Tim,

I looked up a couple of those videos, and they're all already on the site. Once a video has been published on the site adding new labels to it in ooyala does nothing.

If you want to get someone to go into the Sports Show admin and re-categorize the videos that will get those videos in the proper categories. http://sportsshow.denverpost.com/wp-admin/edit.php

-Joe
