### ISSUE TITLE
Sports Show Catergories not correct.

### ISSUE THREAD

**Issue by utahras** [denverpost/dptv#147]
I've reworked this to make as little changes as possible but this is not working correct and we cannot change the labeling workflow until it is fixed. Not sure where the effort lies, with Joe or Dan But we are waiting to fix a messed up labeling issue, but need this part of it.

THE SPORTS SHOW page
Categories for bottom of page these labels are in Ooyala. Top to bottom, left to right.

The Sports Show
Sports Show am (JUST NAME CHANGE)
Sports

Woodys World
Full Episodes
More with Les

Guests
Pick 6
You Gotta See This!

** Pop-A-Shot
** The Big Stuff
** Social Animals

NFL/Broncos
NBA/Nuggets
MLB/Rockies

NHL/Avalanche
** DPtv (replace Up To Date with this)
News

These are what is in the pods now for the player

Full Episodes
The Big Stuff
Woody’s World
Sports
Guests
More With Les
Pick 6
Pop-A-Shot
Social Animals
You Gotta See This!

**Comment by freejoe76** [comment]
Hi Tim, I made the changes to the categories that are on the page that you requested. Right not I can't re-order the categories. If there's anything else please open a ticket, thanks.
