### ISSUE TITLE
Add DPTV newsletter signup form to DPTV home, article pages

### ISSUE THREAD

**Issue by ericjlubbers** [denverpost/dptv#149]
Would like the form included here would be included in every article template as well as somewhere on the home page.

Code for the signup form (styling classes are from Foundation, but we can change to match styling of DPTV):
```
<h4>Get DPTV clips delivered to your inbox:</h4>
<script type ="text/javascript">
    document.write('<style type="text/css"> \n\
        #mj-tease {} \n\
        #mj-tease .mj-form { width:100%; display:block; } \n\
        #mj-tease .mj-form p { margin: 0; display:block; } \n\
        #mj-tease .mj-form input[type=text] { clear:both;  } \n\
        #mj-tease .mj-form input[type=submit] {clear:both; } \n\
        #mj-tease h2 {  } \n\
    </style>')
</script>

<div id="mj-tease" style="padding-bottom:12px;">
    <div class="mj-form">
        <form action="http://denverpostplus.com/app/mailer/" method="post" name="dptv" style="margin:0;">
            <input type="hidden" name="keebler" value="goof111" />
            <input type="hidden" name="goof111" value="TRUE" />
            <input type="hidden" name="redirect" id="inputRedirURL" value="http://extras.denverpost.com/signup/dptvthanks.html" />
            <input type="hidden" name="id" value="autoadd" />
            <input type="hidden" name="which" value="dptv" />
            <input type="text" name="name_first" value="Humans: Do Not Use" style="display:none;" />
            <p style="height:75px;padding-bottom:12px;text-align:center;"><input placeholder="Email Address" type="text" name="email_address" maxlength="50" value="" />
                <input class="button radius expand" type="submit" name="submit" value="SIGN ME UP!" />
            </p>
            <p>&nbsp;</p>
            <div class="clear"></div>
        </form>

        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>
```

**Comment by freejoe76** [comment]
The functionality for this newsletter signup already exists, right?

**Comment by ericjlubbers** [comment]
Totally. That code in the issue is live (it's the code from this page:
http://dpo.st/DPTVupdates) and ready to go, it just needs to be placed
somewhere and slightly styled to match the site.

Eric J. Lubbers
Mobile Editor - The Denver Post
elubbers@denverpost.com / 303-954-2615 / @ericjlubbers
<http://twitter.com/ericjlubbers>

**Comment by freejoe76** [comment]
Okay this is done. The newsletter is present in the footer on every page. Example: http://dptv.denverpost.com/2015/02/06/reaction-shot-2-5-15-jupiters-ascending-mov/

**Comment by ericjlubbers** [comment]
Awesome. Looks like it's breaking to two lines. You can change the SIGN ME
UP language to SIGN UP if that would help the width.

Eric J. Lubbers
Mobile Editor - The Denver Post
elubbers@denverpost.com / 303-954-2615 / @ericjlubbers
<http://twitter.com/ericjlubbers>

**Comment by freejoe76** [comment]
Okay that's fixed.
