### ISSUE TITLE
Add social tools to next videos

### ISSUE THREAD

**Issue by rebeccarisch** [denverpost/dptv#150]
When a video is played in a dptv post (not the homepage), it then goes to the next video and reloads the page. However, the page for the next video that plays has no sharing tools. Can we add those please?

**Comment by freejoe76** [comment]
Hi Becky, the page doesn't reload it just updates the headline and URL and page title, which is why the social buttons disappear (otherwise they'd be sharing the previous page/video's information). Replacing the share tools isn't a simple thing to do, and I'll look into it.

**Comment by freejoe76** [comment]
This is done on DPTV on the in-player social buttons, both iframe and regular-site.

**Comment by freejoe76** [comment]
Okay, this is done on Sports Show, both iframe and regular-site.

**Comment by freejoe76** [comment]
This is done.
