### ISSUE TITLE
When viewed on a phone, make mobile player sized to 16:9 aspect ratio

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#156]
The video player on an article page in DPTV/Sports Show is set to the proper width, but not to the proper height, when viewed on a mobile phone. @schneidan has figured out a way to do this on our blogs when we have video there. I'd like for us to ensure that the player is set to 16:9 aspect ratio.

http://sportsshow.denverpost.com/2015/02/16/rockies-spring-training-rich-in-good-stories/

**Comment by schneidan** [comment]
Joe, if you'd like I can show you how I manage responsive video players in other templates.

**Comment by freejoe76** [comment]
This is done.
