### ISSUE TITLE
Sports Show a.m. autopost problem

### ISSUE THREAD

**Issue by thejoenguyen** [denverpost/dptv#161]
We've been having a problem with the Sports Show a.m. videos coming over to Wordpress. I've tried the run autopost options in the Ooyala Autopost Admin on The Sports Show WP, but none seem to come over.

**Comment by freejoe76** [comment]
I'm looking at this now.

**Comment by freejoe76** [comment]
We had the wrong label id associated, that's fixed now.

**Comment by danielpetty** [comment]
Re-opening this issue because it's still happening.

**Comment by freejoe76** [comment]
Can you tell me how many labels in ooyala are associated with the most-recent sports show am video? cc @danielpetty @thejoenguyen

**Comment by freejoe76** [comment]
per petty: "Two: "Sports Show AM" and "YouTube Sports Show" all of the AM videos have that label scehem"

**Comment by freejoe76** [comment]
So, I ran the autopost by hand for Sports Show AM, and this is what the script returned -- all these videos already are in posts on the site:

```
Looking up video id hycGk0cjrrjuGVy4Ua-9gE2UyXj3P-AM.

Found a post with that video_id, 172.

Looking up video id FqNDU2cjqIQrkN4xvmmHaNekPzTyxv5a.

Found a post with that video_id, 190.

Looking up video id g1eTU2cjqNVo1y8_xNguml932zxP0gUh.

Found a post with that video_id, 192.

Looking up video id 5xbDc2cjpBDCsdLmcND8dJX2vp8NketR.

Found a post with that video_id, 194.

Looking up video id BidHU2cjo84YlKm3BEinj004lzlbFyp-.

Found a post with that video_id, 206.

Looking up video id ZxNnc2cjpDeFXLx_-jLF21UkvTplXoL5.

Found a post with that video_id, 208.

Looking up video id NuYmw3cjo6L5pSgghP_lPMLfjC2oyfts.

Found a post with that video_id, 216.

Looking up video id 8zdGw3cjrWYAqjb6f7m5ujd3PviRl9jn.

Found a post with that video_id, 220.

Looking up video id 1wMGI4cjpjn_3mQYoZlWQOG0ldPZhfn9.

Found a post with that video_id, 228.

Looking up video id x5OWI4cjqWzZZ8uHtnM3ajUUTmdd_Ipo.

Found a post with that video_id, 230.

Looking up video id 5nbTU5cjpqI3ts9ENK9XRGq8WY0UjmsC.

Found a post with that video_id, 240.

Looking up video id trMnFhcjqyOdftAhLR9xDlTxJD88cMFv.

Found a post with that video_id, 253.

Looking up video id toOWZicjoz_Pm6TnCGiWhst-wGArpbYg.

Found a post with that video_id, 285.

Looking up video id 9yOGdicjqWPHkZXz8ichHljByN2UDV6Z.

Found a post with that video_id, 290.

Looking up video id FsdTVjcjru2yuwleqNXBUTzcA6b10lhU.

Found a post with that video_id, 327.
```

**Comment by freejoe76** [comment]
Oh weird, it's looking up pressbox videos. Last week I switched the label id to the SS A.M. label, but something else must be wrong.

**Comment by freejoe76** [comment]
Okay looks like I still had the wrong label id in there for Sports Show AM, I updated the label and pushed those chagnes to prod. Re-open this if it doesn't work tomorrow.
