### ISSUE TITLE
Add Jetpack Plugin to DPTV and Sports Show

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#162]
For Akismet and Wordpress stats

**Comment by freejoe76** [comment]
Hi Dan,

I added these plugins and activated them. However: 

JetPack says it requires a hookup to a WordPress.com account ( there's a link to the wp.com login here: http://dptv.denverpost.com/wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s= ), do you know what should go in there?

Also, Sports Show asks for the same thing ( http://sportsshow.denverpost.com/wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s= )

**Comment by freejoe76** [comment]
Closing this, further configuration can be done by production staff.
