### ISSUE TITLE
Swap out old Press Box on homepage for Sports Show AM

### ISSUE THREAD

**Issue by SaraGDP** [denverpost/dptv#165]
@danielpetty @ericjlubbers @freejoe76 @utahras

Reconfigure press box widget DPTV homepage to feed Sports Show AM wordpress category

**Comment by freejoe76** [comment]
Welcome to Github, @SaraGDP

**Comment by freejoe76** [comment]
Here's the link for easy clicking http://dptv.denverpost.com/

**Comment by freejoe76** [comment]
Hi Sara, this is finished.

**Comment by SaraGDP** [comment]
Content in front page widget still old @freejoe76 http://dptv.denverpost.com/

**Comment by freejoe76** [comment]
Thanks Sara looking at it right now.

**Comment by freejoe76** [comment]
Hi Sara, I fixed the issue and tested it and Sports Show AM videos are now being ingested. There is also an option in the admin to pull them in on the page where all the other manual video-add links are. The new posts are now in DPTV, in draft status. Thanks for your patience and for following up.
