### ISSUE TITLE
AD SETS

### ISSUE THREAD

**Issue by utahras** [denverpost/dptv#166]
Hey Joe I ask this question of Ooyala support and below is their answer, If possible it would be great to set it up so when a label is applied the ad set is also applied. Thanks RAS 

In Backlot we have set up many different Ad Sets, It there a way or could there be a way to have an AD Set applied to a video title when the label is applied? 

For instance when a label News is applied the AD set DP News is set.

Ooyalas response:

Hello Tim,

Thank you for contacting Ooyala Technical Support. I'm taking ownership of this case. Currently we don't offer this option out of the box, but an idea comes to my mind on how you could implement this.

You would have to make use of our API. First you would have to build a logic that that would return the assets of your backlot:

You can do this with the following API Call:

[GET] /v2/assets/

And then check the Label assigned to the video:

You can do this with the following API Call:

[GET] /v2/assets/:EMBED_CODE:/labels

If the label assigned to this video equal the label that you specify, then you can change the ad_set_id assigned to this video with a PATCH call

[PATCH] /v2/assets/U5cWN3czpW1zzYAngTWmubnk7SsRYp1e

{
"ad_set_id": :AD_SET_ID:
}

Please let me know if you have any questions.

Cristian Melendez
Product Support Engineer

**Comment by freejoe76** [comment]
Thanks for filing an issue, Tim. Once and AdSet is set, will it need to be changed again? If so, when?

Also: Where do I get the AD_SET_ID value?

I'm coming into this pretty blind, and I do appreciate the thoroughness of your issue, I just have a couple more questions.

**Comment by freejoe76** [comment]
From Tim: Adset ID's won't change once set. He doesn't know where the AD_SET_ID value comes from.

**Comment by freejoe76** [comment]
We need to know where the ad set id values come from. Meghan, any idea?
