### ISSUE TITLE
DPTV iframe parameter to start video on mute

### ISSUE THREAD

**Issue by ericjlubbers** [denverpost/dptv#170]
Add a parameter sound=mute (or whatever) to add to our current iframe to allow for autoplay video without sound when video is embedded on an article page or other place where unwanted sound might not be appreciated.  @freejoe76 @saragdp

**Comment by ericjlubbers** [comment]
Prerequisite to solving this issue is #140

**Comment by freejoe76** [comment]
I'm working on this, and I just learned that muting the volume *will not* mute the ads. ¯\_(ツ)_/¯

**Comment by freejoe76** [comment]
Filed a ticket with Ooyala ( https://ooyalacommunity.force.com/CaseDetail?id=50070000015aDIp ), on hold until that is resolved.

**Comment by freejoe76** [comment]
From Ooyala:

```"I have validated the issue with HTML5 and I have also found that this is a known issue and its currently set up to be worked during Q2 of this year however I have not received any definite ETA on the fix "```

**Comment by freejoe76** [comment]
We're on hold until Ooyala fixes the known issue.

**Comment by freejoe76** [comment]
Ooyala plans on releasing changes that allow this to happen sometime in 2016.
