### ISSUE TITLE
Create stubs from dptv

### ISSUE THREAD

**Issue by rebeccarisch** [denverpost/dptv#171]
It would be great if we could create stubs that would generate new articles in NGPS that link back to their dptv posts in WordPress, like we do for blogs.

How difficult is this?

**Comment by freejoe76** [comment]
Hi Becky,

I don't know anything about the requirements for stubs. Do you know who would? How did we do this for the blogs? cc @schneidan 

Joe

**Comment by rebeccarisch** [comment]
Schneider, I can't remember who the main contact you worked with was.
Wasn't there just a spreadsheet that we could add new blogs to and then
we'd request by filing a ticket  that they be activated?

On Thu, Mar 26, 2015 at 12:13 PM, Joe Murphy <notifications@github.com>
wrote:

> Hi Becky,
>
> I don't know anything about the requirements for stubs. Do you know who
> would? How did we do this for the blogs? cc @schneidan
> <https://github.com/schneidan>
>
> Joe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denverpost/dptv/issues/171#issuecomment-86653040>.
>



-- 
Rebecca Risch
Digital Director, The Denver Post
rrisch@denverpost.com
303.954.1913
@rebeccarisch <http://www.twitter.com/rebeccarisch>
@denverpost <http://www.twitter.com/denverpost> / fb.com/denverpost
<http://facebook.com/denverpost> / g+/denverpost
<https://plus.google.com/u/1/+DenverPost/posts>

**Comment by freejoe76** [comment]
From @schneidan:
> That was just for the initial setup. I worked with Andre on that, Joe, but he's obviously doing other things now. The process now is to file a ticket with the blog name, feed url (must includes MRSS tags with images and some Dublin Core tags), and the keyword to use in NGPS (I.e. dpBlogTheSpot). Good luck; I've been trying to get the tech blog stubs fixed since before the name changed and my tickets are still in Unassigned.

**Comment by freejoe76** [comment]
Dan (@schneidan), I found this reference to Dublin Core tags ( http://wiki.dublincore.org/index.php/User_Guide ), but I don't know which ones you're talking about. Do you have an example of what you were using?

**Comment by schneidan** [comment]
Yeah, I think it's publisher and site name? It's all. In my RSS tweaks plugin: https://gist.github.com/schneidan/fef644fe7785e65f3bfd





Daniel J. Schneider
Photographer and Journalist
Denver, Coloradohttp://www.scrollwright.com

twitter.com/schneidan

720.732.1763

**Comment by freejoe76** [comment]
Cool, looks like your plugin Dan is already on DPTV and Sports Show.

**Comment by schneidan** [comment]
Awesome. Just give them the feed URL http://dptv.denverpost.com/?feed=full



Daniel J. Schneider
Photographer and Journalist
Denver, Colorado
Scrollwright.com
twitter.com/schneidan <http://www.twitter.com/schneidan>
P: 720-732-1763

**Comment by freejoe76** [comment]
Thanks Dan. I opened a ticket with MNGi.

**Comment by rebeccarisch** [comment]
Thanks guys!

**Comment by freejoe76** [comment]
This part of the stubs work is done.
