### ISSUE TITLE
Embedded version leaving lots of whitespace below, video not filling frame

### ISSUE THREAD

**Issue by schneidan** [denverpost/dptv#173]
See example in header position on: http://www.denverpost.com/news/ci_27790764/coroner-oklahoma-man-killed-self-keystone-after-eating

**Comment by freejoe76** [comment]
Hi @schneidan I'm working on this, but in the meantime could you get me the markup from a DPTV in-article freeform created in November or December? Just want to compare. Thanks~

**Comment by freejoe76** [comment]
This was a problem with code I introduced this week to improve the aspect ratio on mobile. It's fixed.
