### ISSUE TITLE
Ooyala autopost Wordpress script seemingly slowing down over time

### ISSUE THREAD

**Issue by ericjlubbers** [denverpost/dptv#176]
The Ooyala autopost script on the Wordpress side seems to be getting slower and slower. Could it be improved by limiting the search? Or is it already limited? @rebeccarisch @freejoe76

**Comment by freejoe76** [comment]
How slow is it now? It queries the two most-recent videos for each label we're publishing, so the more labels the longer it will take. Also, for each video it looks to see if that video has already been published, so the more posts in WordPress the longer that query would take ... though we should only be talking about fractions of seconds here.

**Comment by ericjlubbers** [comment]
It can take up to 15 minutes between labeling in Ooyala and the script
picking it up (even with manually running the script). Should we be just
using the label we're expecting to see (like, just Up to Date) to reduce
the load?

Eric J. Lubbers
Mobile Editor - The Denver Post
elubbers@denverpost.com / 303-954-2615 / @ericjlubbers
<http://twitter.com/ericjlubbers>

**Comment by ericjlubbers** [comment]
I should clarify that the script runs in just a few seconds, but it just
doesn't find videos that have been labeled even 10 minutes before it
started.

Eric J. Lubbers
Mobile Editor - The Denver Post
elubbers@denverpost.com / 303-954-2615 / @ericjlubbers
<http://twitter.com/ericjlubbers>

**Comment by freejoe76** [comment]
Yea, to cut down on the autoplay I added some logic to make sure the script never ran at the same time twice (which means some of those times you re-run it you're not really re-running it). Thing is, I added that logic like two months ago.

This sounds like an issue though.

**Comment by freejoe76** [comment]
Okay, I looked at the code and it turns out the manual post-videos circumvent the never-run-twice mechanism, so that's not it.

**Comment by freejoe76** [comment]
I'm going to write a script that looks at the timing of when the videos actually show up in ooyala's feed. This may be an ooyala issue.

**Comment by freejoe76** [comment]
Is this still an apparent issue, Eric?

**Comment by ericjlubbers** [comment]
I haven't produced DPTV for the last few days. I will test it at 5.

Eric J. Lubbers // Mobile Editor // The Denver Post

**Comment by freejoe76** [comment]
How'd the test go?

**Comment by freejoe76** [comment]
Is this still happening?

**Comment by ericjlubbers** [comment]
I finally got a chance to do some live production yesterday, and in the six
times I used the scripts, none took more than 90 seconds. I think we can
close this.

Eric J. Lubbers
Mobile Editor - The Denver Post
elubbers@denverpost.com / 303-954-2615 / @ericjlubbers
<http://twitter.com/ericjlubbers>

**Comment by freejoe76** [comment]
Super!
