### ISSUE TITLE
iFramed videos are no longer auto-advancing to the next video

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#177]
Once a video completes, the next video is not automatically playing, per requested functionality. See example below:

http://www.denverpost.com/nuggets/ci_27857771/spencer-haywood-dikembe-mutumbo-elected-basketball-hall-fame

**Comment by freejoe76** [comment]
This is fixed. Also, it was introduced with some javascript I wrote mid-March in one of my attempts to fix the video-skipping auto-next issue.
