### ISSUE TITLE
New Sports Show categories

### ISSUE THREAD

**Issue by JimmyOrrSportsShow** [denverpost/dptv#178]
We've started two new segments on the Sports Show.

Colorado Rapids and MLS
and
Horse Racing

Would you please create these two new categories on the Sports Show page.  And create these on the SportsShow YouTube page?

Thank you very much.

**Comment by freejoe76** [comment]
Hi, thanks for the issue Jimmy. I'm not the one to ask about YouTube, and I don't know who is.

I've created the categories in WordPress, and when videos start getting assigned in Ooyala I'll hook the video feed up to those categories.

**Comment by JimmyOrrSportsShow** [comment]
Do I need to do anything else or contact anyone else?  I will talk to Amy
about YouTube.

**Comment by freejoe76** [comment]
Nope, thanks!

**Comment by freejoe76** [comment]
Okay Rapids videos are hooked up to the Sports Show category, but it doesn't look like there are any posts in horse racing yet so I'm going to close this ticket and if you could open it when a horse racing video goes through that would be great.

**Comment by JimmyOrrSportsShow** [comment]
Here's the horse racing one.
http://sportsshow.denverpost.com/2015/04/09/john-horowtiz-talks-the-kentucky-derby/
