### ISSUE TITLE
Ooyala ad wraps need to be updated to consistently display preoll

### ISSUE THREAD

**Issue by rebeccarisch** [denverpost/dptv#180]
From the ticket:

As a follow-up to your case 00248611 the below comment has been added.

Hi Tim, 

I've had a look at your page and I think I found the issue, the problem is that for mobile the AdTag is a wrapper and the AdTag contained is wrongly encoded. 

What is a wrapper? 
A VAST wrapper is a VAST response that does not contain a VAST inline ad but instead contains information about a redirect to a third party ad server. 

This is the wrongly encoded AdTag: 
http://ad.afy11.net/ad?enc=4&amp;asId=2000002100107&amp;sf=0&amp;ct=256&amp;sr_k5=exadtag_2000004454015_2000030485809 

it should be: 
http://ad.afy11.net/ad?enc=4&asId=2000002100107&sf=0&ct=256&sr_k5=exadtag_2000004454015_2000030485809 

And this is why the player doesn't show an AD for the mobile player. 

To get rid of this issue, please modify the AdTag in the wrapper for the right one, Could you please give that a try and see if it works? 

Please feel free to add any comment/question about this, I'll be happy to help. 

Kind regards, 
Raul Flores

**Comment by freejoe76** [comment]
Okay, I looked and didn't find that code in any of the javascript on the DPTV site. I'm getting Tim's old support tickets moved to Meghan's support account with Ooyala, once that happens I can follow up with them and ask where this code exists.

**Comment by freejoe76** [comment]
This has been taken care of.
