### ISSUE TITLE
Horse racing video to please be inserted into new horse racing category

### ISSUE THREAD

**Issue by JimmyOrrSportsShow** [denverpost/dptv#181]
Here is the URL

http://sportsshow.denverpost.com/2015/04/09/john-horowtiz-talks-the-kentucky-derby/

**Comment by freejoe76** [comment]
Hi Jimmy, I still don't see the Horse Race label in the Ooyala list of labels. Can you make sure that label has been created in Ooyala?

**Comment by danielpetty** [comment]
Need to request this from Eric Lutzens

**Comment by freejoe76** [comment]
Okay emailed Lutzens.

**Comment by freejoe76** [comment]
Thanks Petty, Lutzens just created one. Does Lutzens always create them? Is there a producer assigned to Ooyala? Who can I lean on for ooyala production help?

**Comment by danielpetty** [comment]
I believe Lutzens and Vince (and Meghan) are the only three allowed to create them at the moment.

**Comment by freejoe76** [comment]
Cool. What's the workflow for communicating a new label needs to be created? 

I ask because it's a lot easier for Jimmy to ask Lutzens or Meghan or Vince than it is for him to ask me so I can ask Lutzens or Meghan or Vince.

**Comment by freejoe76** [comment]
This is finished. Jimmy, when you want a new category please ask Lutzens, Meghan or Vince to create the ooyala label and then open an issue here. Thanks!

**Comment by JimmyOrrSportsShow** [comment]
Great. Thanks.
