### ISSUE TITLE
Create a Theater Shooting Category on DPTV

### ISSUE THREAD

**Issue by rebeccarisch** [denverpost/dptv#185]
Would like to replace the SportsShow AM spot for now. Will likely move up using the widget tool when it's ready.

**Comment by freejoe76** [comment]
Hi Becky,

Has this label been created in Ooyala and are there any videos assigned to it?

Thanks
Joe

**Comment by rebeccarisch** [comment]
I don't think there will be any videos until next week at earliest. I can
create a label. Should I just put under dptv?

On Fri, Apr 17, 2015 at 3:51 PM, Joe Murphy <notifications@github.com>
wrote:

> Hi Becky,
>
> Has this label been created in Ooyala and are there any videos assigned to
> it?
>
> Thanks
> Joe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denverpost/dptv/issues/185#issuecomment-94082690>.
>



-- 
Rebecca Risch
Digital Director, The Denver Post
rrisch@denverpost.com
303.954.1913
@rebeccarisch <http://www.twitter.com/rebeccarisch>
@denverpost <http://www.twitter.com/denverpost> / fb.com/denverpost
<http://facebook.com/denverpost> / g+/denverpost
<https://plus.google.com/u/1/+DenverPost/posts>

**Comment by rebeccarisch** [comment]
Correction. There currently IS a label - Aurora Theater (under News).

There are some  old videos already there to use for testing. They look like
ones from the migration from Brightcove.

On Fri, Apr 17, 2015 at 3:53 PM, Rebecca Risch <rrisch@denverpost.com>
wrote:

> I don't think there will be any videos until next week at earliest. I can
> create a label. Should I just put under dptv?
>
> On Fri, Apr 17, 2015 at 3:51 PM, Joe Murphy <notifications@github.com>
> wrote:
>
>> Hi Becky,
>>
>> Has this label been created in Ooyala and are there any videos assigned
>> to it?
>>
>> Thanks
>> Joe
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/denverpost/dptv/issues/185#issuecomment-94082690>.
>>
>
>
>
> --
> Rebecca Risch
> Digital Director, The Denver Post
> rrisch@denverpost.com
> 303.954.1913
> @rebeccarisch <http://www.twitter.com/rebeccarisch>
> @denverpost <http://www.twitter.com/denverpost> / fb.com/denverpost
> <http://facebook.com/denverpost> / g+/denverpost
> <https://plus.google.com/u/1/+DenverPost/posts>
>
>


-- 
Rebecca Risch
Digital Director, The Denver Post
rrisch@denverpost.com
303.954.1913
@rebeccarisch <http://www.twitter.com/rebeccarisch>
@denverpost <http://www.twitter.com/denverpost> / fb.com/denverpost
<http://facebook.com/denverpost> / g+/denverpost
<https://plus.google.com/u/1/+DenverPost/posts>

**Comment by freejoe76** [comment]
Regarding which label and where it goes, under DPTV is fine and makes sense, yeah.

**Comment by freejoe76** [comment]
Okay I hooked up the theater shooting ooyala label to the theater shooting category. The widget still needs to be created, let me know if you want help with that.

-Joe
