### ISSUE TITLE
Figure out how many distinct players we're using

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#194]
per @rebeccarisch

**Comment by freejoe76** [comment]
Sorry Becky I kept for getting to do this so I created this issue to remind me.

**Comment by freejoe76** [comment]
Existing Player IDs:

ca7d0fce12a34a1d8440f09617dddf16
35668554559a48ad8947aa72aed5cdd4
df3e4364f37c45d09283f7d098c03fce
c8b74daf3c534281bc8ba1914c8e01e7
f6a4b508825f4e8594a0732d7d6040f1
aceb741323cd43cc820ce3ea8ed4d44e

**Comment by rebeccarisch** [comment]
THanks Joe. Let's close this one.

**Comment by freejoe76** [comment]
But I haven't figured out where these are being used.
