### ISSUE TITLE
Cannabist Show full episodes are not feeding to YouTube

### ISSUE THREAD

**Issue by AletaLabak** [denverpost/dptv#195]
Hi Joe,
Apologies if this is already on your radar via Amy Brothers. 

Clips for The Cannabist Show that have a YouTube label in Ooyala are making it there, yet the full episodes are not. Weird, eh? We've been producing them all the same way, and there were no instances of removing labels and restoring them (Amy mentioned that can affect publication to YouTube)

One note: For ease of production, we had been pasting in the copy that Ricardo wrote for the posts into the Ooyala description, there were some <em> tags and hyperlinks in there. Just mentioning that in case it's a factor? However in the following examples, one has tags and the other does not -- neither made it to YouTube  

Here are a couple of the recent full episodes that didn't publish to YouTube.
(let me know if you need more/different info):

Cannabist Show: He throws big weed parties; She's a legalization consultant
Content ID: 
J4bzR4dDpzDeanjEgEPqoGufXtAt7zgW

Cannabist Show: He's a Pulitzer finalist; She runs pot shops; He's a weed lawyer
U3bXZzdDqFd3zlN7gaY7OytuDiYpjhpC

**Comment by freejoe76** [comment]
Closing.
