### ISSUE TITLE
Live video player doesn't play when shared on Facebook

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#197]
The live streaming player from Ooyala doesn't appear to play in Facebook. When the URL is run through the Facebook debugger, this is the issue:

Object at URL 'http://sportsshow.denverpost.com/2015/05/29/watch-the-sports-show-live-with-woody-paige-and-les-shapiro-for-may-29-2015/' of type 'video.other' is invalid because a required property 'og:image:url' of type 'url' was not provided.

**Comment by freejoe76** [comment]
Do you have a featured image associated with the post?

**Comment by freejoe76** [comment]
Opened an issue with ooyala https://ooyalacommunity.force.com/casedetail?Id=5007000001D4e6GAAR

**Comment by freejoe76** [comment]
You can see the livestream trying to play here: https://www.facebook.com/pages/Digging-In/103278966385184

**Comment by freejoe76** [comment]
Hey Petty the video_id field was blank in the blog post. How was that post created?

**Comment by danielpetty** [comment]
Ahh, it was cloned over from a previous post. Need to be sure that's in
there.

**Comment by freejoe76** [comment]
Yup. Closing this issue.
