### ISSUE TITLE
Map MLS/Rapids to MLS and Rapids category in Sports Show wordpress

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#202]
Requesting to map the MLS/Rapids Ooyala tag under "The Sports Show" to the "MLS and Rapids" category in the Sports Show Wordpress.

**Comment by freejoe76** [comment]
Ok working on that now. It's label id 0bc5ad7adaff4ddaacba3c1199be5d52

**Comment by freejoe76** [comment]
Okay this is done. Thanks for the ticket.
