### ISSUE TITLE
Sports Show segments not loading on samsung galaxy

### ISSUE THREAD

**Issue by JimmyOrrSportsShow** [denverpost/dptv#203]
Reader (chris.leeper@yahoo.com) writes:

Good afternoon Jimmy,

None of the segments will load for me via the mobile site.  I'm using strong wifi connection on a samsung galaxy.  I've tried other devices with no luck. I've tried various browsers and links.  I've provided a screen shot of what I'm seeing.  

Let me know if I can be of anymore assistance.  

Chris

**Comment by freejoe76** [comment]
This is one of the videos Chris was having problems with: http://sportsshow.denverpost.com/2015/06/03/are-the-rockies-wasting-troy-tulowitzki/ . It's not a livestream video, for reference (see https://github.com/denverpost/dptv/issues/193 ).

**Comment by freejoe76** [comment]
Fixed.
