### ISSUE TITLE
Change color of links on DPTV

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#206]
I'm wondering if the light brown color of links is maybe too light and not definitive enough. Had a few editors ask me about this, and how it's hard to see the links within the description text. Does light blue make sense to match DPTV?

http://dptv.denverpost.com/2015/06/24/what-does-a-cirque-du-soleil-performer-see-way-up-high-go-behind-the-scenes-of-kurious/

**Comment by freejoe76** [comment]
This is done. http://dptv.denverpost.com/2015/07/01/ever-olivos-gutierrez-sentenced-family-of-juan-carlos-dominguez-palomino-speaks-after/
