### ISSUE TITLE
Embed code popup does not appear when video embedded on denverpost.com

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#210]
When a DPTV or Sports Show video is embedded in an article or blog post on denverpost.com (i.e., outside of dptv.denverpost.com or sportsshow.denverpost.com), when a user clicks to embed code button on the iframed player to get embed code, a pop-up does not show up. 

Example: http://www.denverpost.com/nuggets/ci_28459211/lebron-james-signs-2-year-deal-cleveland-cavaliers

The popup DOES show up when the button is pressed inside dptv.denverpost.com or sportsshow.denverpost.com.

DP

**Comment by freejoe76** [comment]
Fixed.
