### ISSUE TITLE
Broncos video FF

### ISSUE THREAD

**Issue by BeetBailey** [denverpost/dptv#221]
The framing on the Broncos video looks a bit off. Please take a look. Thanks 
![bronx-video](https://cloud.githubusercontent.com/assets/9666943/9076378/c2fed1d0-3ade-11e5-8c80-dd8431a16a08.jpg)

**Comment by freejoe76** [comment]
I'm working with ooyala on this.

**Comment by freejoe76** [comment]
This is fixed: http://www.denverpost.com/broncos
