### ISSUE TITLE
Update RSS adds plugin

### ISSUE THREAD

**Issue by schneidan** [denverpost/dptv#233]
Latest version: https://gist.github.com/schneidan/fef644fe7785e65f3bfd

**Comment by freejoe76** [comment]
Hi Dan, I pulled from repo and promoted to production on DPTV and Sports Show -- can you check and make sure it's working as intended?

**Comment by schneidan** [comment]
Is there another repo than the gist I linked above? I see two copies of v0.2b on DPTV, but it should be v0.6b

**Comment by freejoe76** [comment]
Huh:

```
[submodule "dp-rss-additions"]
	url = git@gist.github.com:/fef644fe7785e65f3bfd.git
```

**Comment by schneidan** [comment]
Weird. Maybe I should just make an actual repo out of it instead of a gist?

**Comment by schneidan** [comment]
Or could it have something to do with the fact that there appear to be two copies installed?

<img width="811" alt="dprss2x" src="https://cloud.githubusercontent.com/assets/1051561/9909708/960d0f90-5c56-11e5-9ac5-194c6b3dbb42.png">

**Comment by freejoe76** [comment]
Whoops, it was a problem on not pulling the most-recent version on the beta machine. It's fixed and deployed. Thanks dude!

**Comment by schneidan** [comment]
woot

You've got three checkboxes to help you out in the settings if you need them. I added the Copyright owner. http://sportsshow.denverpost.com/wp-admin/options-general.php?page=dprss_options

**Comment by schneidan** [comment]
Just a heads-up, still seeing the duplicate 0.2 and no current version on DTPV. SportsShow looks good.
