### ISSUE TITLE
Investigate making the embeddable player faster.

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#234]
Re: 
<img width="768" alt="screen shot 2015-09-16 at 8 53 06 am" src="https://cloud.githubusercontent.com/assets/125554/9905045/6f833cba-5c50-11e5-8c6d-e85b2bb13823.png">

**Comment by freejoe76** [comment]
Note: looks like the embedded player usually clocks in at ~3MB (example: http://dptv.denverpost.com/2015/09/24/denver-board-of-ethics-rejects-inspectors-consulting-for-marijuana-industry-and-more/?iframe=1&autoplay=1 )

**Comment by freejoe76** [comment]
@danielpetty got any problem with me killing the Google Plus button site-wide?

**Comment by danielpetty** [comment]
@freejoe76 None at all. Go for it!
