### ISSUE TITLE
DPTV ipad delivery issue

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#235]
via @danielpetty 
Ad delivery on iPad for me for DPTV video is ... sporadic at best. And... it's just not reliable

danielpetty [4:46 PM]
I assume it's the fault of the HTML 5 player

danielpetty [4:47 PM]
but I see a single frame of the ad, and then it tries to advance

danielpetty [4:47 PM]
And then it just freezes

danielpetty [4:48 PM]
This is on dptv.denverpost.com.

**Comment by freejoe76** [comment]
Hi @danielpetty, are there any more details you can give? Is this on the homepage player, or on a post?

**Comment by danielpetty** [comment]
On iPad, when I go to dptv.denverpost.com and try to press play on the main video, I see the first frame of the ad, then it freezes, and it transitions to the first frame of the video, then it freezes. If I want to start the video again, I have to press the play button again, then the video starts playing. It's unclear whether the ad was being counted as played.

One thing: Is it possible to develop a sniffer to turn autoplay for mobile and tablet off on dptv.denverpost.com? It doesn't look like it plays on tablet or mobile for videos embedded in iframes for stories.

**Comment by freejoe76** [comment]
Fixed.
