### ISSUE TITLE
DPTV video not playing on Android

### ISSUE THREAD

**Issue by danielboniface** [denverpost/dptv#236]
http://dptv.denverpost.com/2015/09/21/denver-broncos-week-3-report-by-troy-renck/

When I tap it on my phone it tried to load an ooyala address that has player_v2 in the address.

Works fine on desktop. 

Some other DPTV videos are having the same problem.

Some other DPTV videos that work on mobile instead launch an ooyala address that has an iframe in the url. @freejoe76

**Comment by freejoe76** [comment]
Thanks for the link @danielboniface. What phone are you using, and which version of the OS were you on?

Also can you give me the link to the ones that work?

I tested the URL you sent on an iOS device and it played (albeit without an ad), I tried it on an android (Samsung, kitkat OS), and it exhibited the same behavior described here: https://github.com/denverpost/dptv/issues/203

Regarding ^, I took it up with Ooyala who spent sometime with it and couldn't figure it out. They put the responsibility for fixing it on us. I know that ticket's pretty old.

**Comment by danielboniface** [comment]
@freejoe76 I'm on a Samsung Galaxy S4, running Android version 4.4.4 which I believe is KitKat.

This one worked with an ad: http://sportsshow.denverpost.com/2015/09/21/top-5-nfl-teams-after-week-2/

This did not work: http://dpo.st/1MhCtCc, http://dpo.st/1NBBeiT  

Maybe a difference between Sports Show and DPTV?

**Comment by freejoe76** [comment]
Well, I can't get sportsshow.denverpost.com to load on my android or iOS devices. The site times out. Do you have a link to a dptv video that works on your handheld?

**Comment by danielboniface** [comment]
I just went back through the DPTV twitter feed and the only thing I can get to play on my phone is a sports show clip.

**Comment by freejoe76** [comment]
Great, which one?

**Comment by danielboniface** [comment]
@freejoe76 http://sportsshow.denverpost.com/2015/09/21/top-5-nfl-teams-after-week-2/ this one worked on mobile for me

**Comment by danielboniface** [comment]
@freejoe76 this video is not playing on mobile... was there any resolution on this ticket? http://dptv.denverpost.com/2015/09/28/denver-broncos-week-4-report-by-troy-renck/

**Comment by freejoe76** [comment]
@danielboniface Hi Dan, I've been working on other things. This is still on the list.

**Comment by freejoe76** [comment]
Got a new error message on android: "Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture."

**Comment by freejoe76** [comment]
Android works fine when the video isn't set to autoplay. I'm going to turn off autoplay on android devices.

**Comment by freejoe76** [comment]
Okay, this is fixed.

**Comment by danielpetty** [comment]
@freejoe76 I wonder if it's worth trying this also on iPhone. Because I think that the video tries to start in the same way, then stops. Can we turn off autoplay on all mobile devices?

**Comment by freejoe76** [comment]
@danielpetty Yes, I'll do that.

**Comment by freejoe76** [comment]
@danielpetty okay that's done.

**Comment by freejoe76** [comment]
Fixed
