### ISSUE TITLE
No scrubber, other buttons on flash player in DPTV

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#243]
And in Sports Show (as viewed in Chrome). It DOES appear in the iframed player. Just not on the DPTV and Sports Show pages themselves.

http://dptv.denverpost.com/2015/10/08/colorado-and-federal-agents-cracking-down-on-illegal-marijuana-grows-and-more/

**Comment by freejoe76** [comment]
Fixed. http://dptv.denverpost.com/2015/10/12/the-dmv-may-outsorce-some-services-and-more/
