### ISSUE TITLE
Integrate Tout and NDN/Inform with Chartbeat

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#245]
NDN/Inform says they're ready for us to integrate Chartbeat's video real-time platform. Also seeing if this is possible with Tout videos.

**Comment by freejoe76** [comment]
Chartbeat on NDN was already implemented. I'm working on Tout now.

**Comment by freejoe76** [comment]
Re: Tout, look into this, tout says: http://support.tout.com/how-do-we-track-performance-on-our-video-destination-page/

**Comment by freejoe76** [comment]
We're not really  using Tout, so this issue is done.
