### ISSUE TITLE
NDN feed putting title of video into description of NDN asset

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#247]
NDN feed is working but appears to be not taking the description of the video from Ooyala and only putting the title of the video into the description field.

**Comment by freejoe76** [comment]
@danielpetty When did this start and do you have an example URL of where it's happening now?

**Comment by danielpetty** [comment]
@freejoe76 You need to access the NDN control room internally here: https://control.inform.com/media/search

Password is in Passpack.

**Comment by freejoe76** [comment]
@danielpetty cool, I'm in there but I haven't found any examples of those videos. I tried an advanced search by source, but "Denver Post" is not listed as a video source. "The Denver Post" isn't either. I tried other searches of local news issues but haven't turned up anything. Video id 29832905 is ours, it was published Oct. 20th, and it looks fine. Do you have a video id of a video this is happening on?

**Comment by danielpetty** [comment]
Check this video ID? I'm clicking on "Media Manager" at the top and then clicking the "Enabled" button to see all of our videos. One example is: 29864445

**Comment by freejoe76** [comment]
Okay, I understand what's going on now. I'll file a ticket with NDN and cc you. Depending on the results of this ticket we may get to file one with Ooyala as well.

**Comment by freejoe76** [comment]
Okay, I updated the feed template in Ooyala's backlot, it should be fixed now but I'll keep this issue open until we're sure.

**Comment by freejoe76** [comment]
whoops clicked the wrong button

**Comment by freejoe76** [comment]
This is fixed
