### ISSUE TITLE
Update these plugins:

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#252]
per @schneidan 

dptv.denverpost.com
	WordPress SEO

sportsshow.denverpost.com
	Blubrry PowerPress
 	WordPress SEO

**Comment by freejoe76** [comment]
Okay Blubrry and SEO work fine on Sports Show on beta, DPTV beta didn't have the SEO plugin.

**Comment by freejoe76** [comment]
Hey @schneidan, this is my last hour of work until next week, I'm not going to launch these updates on prod because that's just asking for it.

**Comment by schneidan** [comment]
Good call @freejoe76. Do DPTV and Sports Show beta sites need be updated to match prod? I'm pretty sure DPTV has WP-SEO on prod... I'm happy to help out checking these out asm much as you need. I just don't know your themes and how these plugins might potentially conflict, if at all.
