### ISSUE TITLE
Build a large-file-uploader for the photo department

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#270]
- Ingests a large video file
- Publishes a one-off MRSS feed with video details (title, description) for ingestion by Inform

**Comment by rebeccarisch** [comment]
Joe, we need to make this one a priority. We keep hitting the limit.

**Comment by freejoe76** [comment]
@rebeccarisch I started on it a half-hour ago, I'm working on the code here: https://github.com/denverpost/video-files

**Comment by freejoe76** [comment]
This is done. Any new issues can be opened on the repo, https://github.com/denverpost/video-files
