### ISSUE TITLE
Add ability to share dptv videos inline on Facebook

### ISSUE THREAD

**Issue by danielboniface** [denverpost/dptv#271]
Currently, the Inform videos shared from dptv.denverpost.com do not play.

**Comment by freejoe76** [comment]
Followed up with Inform on this.

**Comment by freejoe76** [comment]
@danielboniface see this: is this good for your needs? https://www.facebook.com/denverfitness/posts/1061581480550818

**Comment by danielboniface** [comment]
@freejoe76 It looks alright, but when you click the play button the video vanishes. At least it does on my computer/Chrome browser.

**Comment by freejoe76** [comment]
Okay I got off the phone with Inform: They say a working FB inline experience is "in the pipeline," and that they have one for twitter and will send me the details on it shortly. cc @danielboniface  @danielpetty

**Comment by freejoe76** [comment]
Here's the twitter share URL, to use it replace the VIDEOID with your actual video's id: https://social.newsinc.com/media/json/69017/VIDEOID/singleVideoOG.html?type=VideoPlayer%2FSingle&widgetId=2&trackingGroup=69017&videoId=VIDEOID
