### ISSUE TITLE
Fix the video on the special projects.

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#272]
per Meghan Lyden

Transgender - This is the priority because of contests:

[ ] Missing Video - http://extras.denverpost.com/transgender/homeless.html IydXJveTr9f7ug--yK8_wJ3peh-au98o
[X] Missing Videos and Photos - http://extras.denverpost.com/transgender/words.html
[X] Missing Video - http://extras.denverpost.com/transgender/culture.html
[X] Missing Photos and Video - http://extras.denverpost.com/transgender/soldier.html
[X] Missing Video - http://extras.denverpost.com/transgender/alison.html
[X] Missing Video - http://extras.denverpost.com/transgender/elsa.html

[ ] Poetry - Everything person has a video - all are broken

http://extras.denverpost.com/poetry-now/index.html

Long Haul

[X] Missing Video - http://extras.denverpost.com/long-haul/video.html

Nine Innings

[ ] Missing video - http://extras.denverpost.com/nine-innings/index.html
[ ] Missing video - http://extras.denverpost.com/nine-innings/inning2.html
[ ] Missing video - http://extras.denverpost.com/nine-innings/inning3.html
[ ] Missing video - http://extras.denverpost.com/nine-innings/inning4.html
[ ] Missing video - http://extras.denverpost.com/nine-innings/inning6.html
[ ] Missing video - http://extras.denverpost.com/nine-innings/inning7.html

Kailyn Forsberg

[X] Missing video - http://extras.denverpost.com/projects/2015/kailyn-forsberg/

That's everything from this year.

cc @schneidan

**Comment by freejoe76** [comment]
This is the line I added to the function that creates the video player ( also, all subsequent js was commented out ): https://github.com/denverpost/transgender/blob/master/js/functions.js#L165

**Comment by freejoe76** [comment]
@schneidan can you handle the rest of the videos on this list?

**Comment by schneidan** [comment]
This is done except for Breakdown and part of Chasing the Beast, which are pending.
