### ISSUE TITLE
Update the Sports Show page header

### ISSUE THREAD

**Issue by danielboniface** [denverpost/dptv#273]
Hello @freejoe76, we need to update The Sports Show header.

sportsshow.denverpost.com

![the-sports-show-with-woody-paige](https://cloud.githubusercontent.com/assets/9724494/12272829/8d4dee08-b91f-11e5-9932-7f50a88c448e.jpg)

**Comment by freejoe76** [comment]
@danielboniface that's a jpeg, can you upload a gif or a png?

**Comment by freejoe76** [comment]
This is done http://sportsshow.denverpost.com/
