### ISSUE TITLE
Transition Sports Show videos to Inform videos

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#277]
Some existing videos are still calling Ooyala URLs:

Not all of these need transitioning, but someone forwarded this URL to me:

http://sportsshow.denverpost.com/2015/12/22/what-is-peyton-manning-s-role-with-the-broncos/

**Comment by freejoe76** [comment]
It's likely that those are videos that were uploaded after we started the import-to-Inform process. Those videos will have to be hunted down in our drobo archive and uploaded to Inform. cc @schneidan

**Comment by schneidan** [comment]
If they are found and uploaded to NDN, and subsequently added to a spreasheet mirroring the one from the import, the embeds in Wordpress can be updated automatically.

**Comment by freejoe76** [comment]
Is this video-sleuthing our job or photo's?

**Comment by schneidan** [comment]
I'm going to call not-it...

**Comment by freejoe76** [comment]
Anyone who does this has to have access to the drobo as well as the DPTV / SS wp-admin. This narrows down the people who can do this. I'm not sure these videos are even on the drobo, I'll ask Meghan.

**Comment by freejoe76** [comment]
I talked with Meghan, her team will handle these updates on a case-by-case basis.
