### ISSUE TITLE
Please add Sports Show video skybox to /superbowl page

### ISSUE THREAD

**Issue by danielboniface** [denverpost/dptv#281]
We'd like to have the Sports Show video skybox on the right (No. 3) skybox on the /superbowl page.

Thanks!

cc @freejoe76 @schneidan

**Comment by schneidan** [comment]
Can't you put the freeform there in the section editor? Or am I missing the issue here?

**Comment by freejoe76** [comment]
If it's the same one as the existing one then yes, we can.

**Comment by danielboniface** [comment]
I was trying to add the same freeform in sections, but I couldn't find it in the dropdown menu. @schneidan @freejoe76

**Comment by danielboniface** [comment]
OK, figured it out and got it switched out.
