### ISSUE TITLE
Add ask the editor playlist

### ISSUE THREAD

**Issue by freejoe76** [denverpost/dptv#282]
Can you add the DPTV. Ask The Editor playlist so that it creates posts automatically?

per @rebeccarisch

**Comment by freejoe76** [comment]
This is done.

**Comment by rebeccarisch** [comment]
Joe, I added two new videos into the Ask The Editor playlist about 25
minutes ago. Should they have made it to dptv posts by now?

On Thu, Jan 28, 2016 at 10:06 AM, Joe Murphy notifications@github.com
wrote:

> Closed #282 https://github.com/denverpost/dptv/issues/282.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/denverpost/dptv/issues/282#event-530001841.

## 

Rebecca Risch
Digital Director, The Denver Post
rrisch@denverpost.com
303.954.1913
@rebeccarisch http://www.twitter.com/rebeccarisch
@denverpost http://www.twitter.com/denverpost / fb.com/denverpost
http://facebook.com/denverpost

**Comment by freejoe76** [comment]
Okay they're in now.
