### ISSUE TITLE
Ensure Sports Show videos from NDN are set to autoplay when imported to Wordpress

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#283]
Videos are currently set to NOT autoplay by default, as they are in DPTV.

http://sportsshow.denverpost.com/2016/02/03/why-the-broncos-will-steamroll-the-panthers-in-the-super-bowl/

**Comment by freejoe76** [comment]
I'll get this done, but when are we sunsetting Sports Show again?

**Comment by danielpetty** [comment]
@freejoe76 The show's future is going to be evaluated after the Super Bowl -- so no timeline, or even a guarantee that it will go away. The site itself won't be sunsetted until we can guarantee that it can get imported into new Wordpress, which is still a few months away.

**Comment by freejoe76** [comment]
Okay thanks -- I pushed the change to beta, it will go live once DFM IT pushes it from beta to prod.

**Comment by freejoe76** [comment]
Okay it's pushed.

**Comment by freejoe76** [comment]
I may not have changed it in the right place, waiting to hear back from Inform.

**Comment by freejoe76** [comment]
Okay there was one more fix to make. It's made, and it's live.

-Joe
