### ISSUE TITLE
Removing the "undefined" videos in Chartbeat analytics

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#285]
We often end up with "undefined" videos in Chartbeat. I filed a ticket with Chartbeat about this, and here is their response.

Hi Dan,

We noticed sometimes in the video dashboard that there are videos that display without a title or thumbnail. This is because there are timing issues where the video strategy is checked before NDN has passed its javascript to our system. Please see the attached screenshot of an example video.

There is a simple fix that should take care of this. By setting _sf_async_config.autoDetect=false; in your _sf_async_config variable this issue should be resolved.

We are still investigating the source of the undefined video titles but we suspect that including this line in your _sf_async_config declaration may fix this as well as it is adversely affecting other videos across your site. Any time an incorrect video strategy is checked against a particular video it is liable to tamper with the ping configuration.

Please let us know if you have any questions about this and we are eagerly awaiting the outcome of this change.

Best,
Will

**Comment by freejoe76** [comment]
Hi Dan, I made the changes to http://extras.denverpost.com/media/js/dputils-min.js?v=9 and those should be live soon.
