### ISSUE TITLE
Add Outbrain to DPTV and Sports Show pages

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#288]
Hi -- Requesting to add Outbrain to DPTV and Sports Show pages, and integrate them well with comments, similar to what we have on the main articles at The Denver Post.

**Comment by freejoe76** [comment]
Hi Dan, it's up on DPTV. I tried to get it on Sports Show but something's busted with moving SS files from beta to prod, and we're sunsetting SS anyway, so I'm not going to put in the effort in getting Outbrain on there. This is done, you can see it live at http://dptv.denverpost.com/2016/03/21/nations-highest-court-rejects-marijuana-case-filed-against-colorado/ .
