### ISSUE TITLE
Allow users to turn autoplay's default to autoplay-off for one month

### ISSUE THREAD

**Issue by danielpetty** [denverpost/dptv#96]
Similar to what ESPN does. Would like people to have the option to have autoplay on/off with the click of a button on the player. If switched to "OFF," would keep all Ooyala DP videos off autoplay for one month, and then reset.

Here's an example: Note the autoplay behavior, assuming you have not turned it off before:

http://espn.go.com/nfl/story/_/id/12073950/denver-broncos-league-high-nine-players-selected-pro-bowl

**Comment by freejoe76** [comment]
Okay I'm picking this up again.
